# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

minecraft_version=1.20.1
yarn_mappings=1.20.1+build.10
loom_version=1.10-SNAPSHOT
minecraft_version_range=1.20.1

# Mod Properties
mod_version=2.0.0-alpha.12
maven_group=io.github.u2894638479
archives_base_name=blue-archive-halo

# Dependencies
forge_version=47.4.6
forge_version_range=[47,)
kff_version=4.3.0

loom.platform=forge
loader=forge
kotlin_serialization_version=1.6.3
kotlinmcui_version=1.0.0-alpha.30
kotlinmcuibackend_version=1.0.0-alpha.15